### ISSUE TITLE
Outreachy internships

### ISSUE THREAD

**Issue by hturner** [r-devel/rcontribution#15]
Various people have expressed an interest in doing an [Outreachy](https://www.outreachy.org/) internship with the R project (by contacting the R Foundation board, or asking on R-Ladies Slack groups). A blocker has been the high [Mentor requirements](https://www.outreachy.org/mentor/#mentor) (5-10 hrs/week during 6 week application period, 5 hrs/week during 3 month internship) and the need to find at least 2 mentors that can commit to this (see [Coordinator duties](https://www.outreachy.org/mentor/#coordinator)). 

However, I think we can make this work by co-mentoring projects (see [FAQ](https://www.outreachy.org/mentor/mentor-faq/)), with the primary mentor being an expert (R Core member/experienced contributor) that volunteers < 1 hour/week and the secondary mentor being someone that can commit to daily supervision. This worked quite well for @SaranjeetKaur's documentation project, with myself and @lawremi meeting with Saranjeet for 30 min each week and myself providing ad-hoc support/documentation review in between (not daily supervision, but similar principle).

Outreachy requires the community (R project in our case) to find $6500 to fund one intern, then we can apply to the general Outreachy fund for another intern. I can commit to regular supervision for one intern under my fellowship and hopefully could pair up with an R Core member/experienced contributor relevant to project. If we had a second intern funded by Outreachy, we could potential pay someone to regularly supervise that project (again pairing with a member of R Core/experienced contributor if additional expertise required). A suitable stipend might be $3000-$6000 for such a supervisor, bring the cost to $9500 - $12500 for two interns, which seems reasonable.

It would also be helpful to have [volunteers](https://www.outreachy.org/mentor/#volunteer) to help during the application phase.

Potential projects, building on our work so far:

 - Triaging Bugs
 - Translating messages in a language that is currently not well covered
 
 Dates: we have just missed out on the current round, so we're now looking at applying in January 2022 for internships running May-August 2022 (or waiting till the round after if that works better for potential mentors).
 
| Important Round Dates                | Mid-year Internships | End of year Internships |
| ------------------------------------ | -------------------- | ----------------------- |
| Call for mentoring communities opens | early January        | early August            |
| Initial applications open            | early February       | late August             |
| Initial applications due             | end of February      | early September         |
| Contribution period opens            | mid March            | early October           |
| Contribution period ends             | mid April            | end of October          |
| Interns announced                    | mid May              | late November           |
| Internships start                    | May                  | December                |
| Internships end                      | August               | March                   |

**Comment by jtelleriar** [comment]
Could "Google Summer of Code" also be within the internship category, in addition to Outreachy?

https://summerofcode.withgoogle.com/

**Comment by hturner** [comment]
@jtelleriar can you open this as a separate issue? I think there are different considerations for the GSoC program, which we could discuss separately.

**Comment by hturner** [comment]
@gmbecker is willing to mentor, so we have enough to come back to this in the new year

**Comment by hturner** [comment]
Our community application is submitted and pending approval: https://www.outreachy.org/communities/cfp/the-r-project-for-statistical-computing/. 

We have till March 23 for mentors to propose projects. 

Current plans:

* A project on bug-tracking (@gmbecker as proposing mentor)
* A project on converting R Journal articles and/or packages vignettes to HTML (me as proposing mentor)
* A Bioconductor project (proposing mentor TBD)

We also have some tentative ideas around translations (standardize and improve the translatability of the English messages, or translating messages in a language that is not well covered, or creating a dashboard to summarise translation status). However this area is not such a good match to available mentors - if anyone would like to volunteer, do let me know!

**Comment by hturner** [comment]
Our application was not approved, so some project ideas were redirected to Google Summer of Code:
 - https://github.com/rstats-gsoc/gsoc2022/wiki/Track-R-Translations-Status 
 - https://github.com/rstats-gsoc/gsoc2022/wiki/Converting-past-R-Journal-articles-to-HTML
