### ISSUE TITLE
Bug Confirmation Hackathon/"Bug Barbeque"

### ISSUE THREAD

**Issue by gmbecker** [r-devel/rcontribution#18]
One idea could be having a ”bug barbecue”, with involvement from R Foundation, or R-core
Probably not to fix things, but to have a big “replication/confirmation” push in a short amount of time with high engagement
As opposed to longer term mentoring, or in addition to it.

I know that the Carpentries run this type of thing one or maybe a couple times a year, I could find out how often. 

The core idea is that you'd have a short span of time (a half day, maybe) with really high engagement, rather than a slow trickle over a long period of time.

I do think it would work better with some amount of R-foundation/R-core involvement, but if a couple different R core members could be involved for an hour or two each over the course of the day and we could get a high number of contributors blocking out that half day or so to focus on helping them out, iteration could get much faster and we might get a lot done. Thats the theory anyway.

**Comment by hturner** [comment]
I think this issue was closed by mistake.

**Comment by MichaelChirico** [comment]
Love the name "bug barbecue"

**Comment by hturner** [comment]
I have contacted the useR! 2022 organizing team suggesting the following sessions on Thursday/Friday June 23/24:

Session 1 (APAC): 
Thursday 20:00-24:00 UTC-5  (Friday 09:00 - 13:00 in Tokyo, Thursday 18:00 - 22:00 in San Francisco)

Session 2 (EMEA):
Friday 04:00-08:00 UTC-5 (Friday 09:00 - 13:00 in Accra, Friday 14:30 - 18:30 in New Delhi)

Session 3 (AMER):
Friday 11:00-15:00 UTC-5 (Friday 09:00 - 13:00 in San Francisco, Friday 19:00 - 23:00 in Nairobi)

See here for most timezones: 
https://docs.google.com/spreadsheets/d/1gdisa5R93EWpXh_mutWezByIRcE_dmm_OnYS-fZOfZ4/edit#gid=0 

Of course this relies on some facilitators being available in each session. It would be great if people could add their name and timezone on the second tab of the above spreadsheet if they are willing to help (I've added a few folks already, please add a note if you can't make the session(s) in your timezone). Put the date in your diary!

I've allowed 4 hours, but expect much of the time to be unstructured drop-in style (maybe zoom rooms open, slack channel available). We could have a kick-off talk for 20-30min at the start which could be live or pre-recorded (same for all sessions) and perhaps a wrap-up time at the end. Maybe short regrouping to check progress after each hour? (N.B. not all time zones will be "on the hour"!).

**Comment by hturner** [comment]
This satellite to useR! went ahead as planned, we should open a new issue for any future Bug BBQ/hackathon.
