### ISSUE TITLE
Review of translation teams

### ISSUE THREAD

**Issue by hturner** [r-devel/rcontribution#28]
Two main tasks:

1. Review general state of translations in R (translations of messages, warnings and errors). 
    - Which languages are being actively maintained?
    - Which languages need most attention? (E.g. ones not updated for several releases of R)
2. Review translation teams
    - Which team contacts are active? Which teams need a new contact/leadership?
    - How to onboard new contributors?

**Comment by MichaelChirico** [comment]
Is this still an open issue? I know at least some progress has been made here...

**Comment by hturner** [comment]
1. We looked at this in the Collaboration Campfire and have a related blog post in the works.

2. We emailed the named contacts for all the translation teams, so have an idea of the status for most of them. There were some updates to https://developer.r-project.org/TranslationTeams.html, but it doesn't show e.g. where the maintainer wants someone else to take the job on. There are still some contacts there that don't work at all. It is also somewhat misleading, because some teams (Dutch, Greek, Portuguese, Ukrainian) have only provided translations for the Windows Installer - yet other languages which have also provided translations for the Windows Installer are not listed. We can ask for another update, but will need to wait till Michael Lawrence is back from sabbatical. Meanwhile, I think we can work with active contacts to create fuller information on the new translations dashboard. This could include the team contact, description of scope (base packages/Windows GUI/Windows Installer/Recommended Packages/MacOS GUI), teams preferred method of working (GitHub/weblate/other), any team resources (webpage/group email), a list of all active team members/translation reviewers. Maybe in time this could replace the page on the developer site, as contributors could directly update information for their team.

So I think it is worth waiting for the blog post and perhaps the end of the GSoC translations dashboard project before closing this.

**Comment by hturner** [comment]
The blog post has now been published (https://blog.r-project.org/2022/07/25/r-can-use-your-help-translating-r-messages/index.html) and I was able to submit some changes to https://developer.r-project.org/TranslationTeams.html along with the post as that page is maintained in the same repo as the blog. These two updates address most of the original issue, further information on the translation teams can come under the translations dashboard project, while on-boarding should probably be considered as a separate issue, likely in relation to the new Weblate server cc @daroczig.
