### ISSUE TITLE
Code of conduct for RCWG events

### ISSUE THREAD

**Issue by hturner** [r-devel/rcontribution#30]
The issue of a code of conduct was raised way back in the kick-off meeting for this group (https://github.com/r-devel/rcontribution/blob/main/team_minutes/2020-07-24.md). While it was considered to be an infeasible goal for the R project in the short term, we should consider at least a code of conduct for RCWG events (that could possibly cover the Slack and RCWG working group as well).

We might use the [Linux Foundation Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/) as adopted by useR!. However, this is focused on large conferences and is perhaps over the top for smaller/informal meetups. I see that Data Umbrella uses the [NumFOCUS code of conduct](https://numfocus.org/code-of-conduct), see e.g. https://pymc-data-umbrella.xyz/en/latest/#pymc-data-umbrella-events. This looks good to me. Is this something we could adopt? Should we look into becoming a NumFOCUS project?

Noting here to follow up later (probably after April if it's down to me).

**Comment by hturner** [comment]
I went to a meeting of the Digital Infrastructure Fund yesterday and they applied the [Contributor Covenant](https://www.contributor-covenant.org/) to the meeting and the work of their [projects](https://digitalinfrastructure.fund/projects/). So that could be another possibility.

**Comment by hturner** [comment]
Other examples of CoC within the R Community:
 - [Bioconductor](https://bioconductor.github.io/bioc_coc_multilingual/)
 - [rOpenSci](https://ropensci.org/code-of-conduct/)

**Comment by yabellini** [comment]
Some others:
* R-Ladies: https://guide.rladies.org/about/coc/
* MetaDocencia: https://www.metadocencia.org/en/cdc/
* LatinR Slack: https://latin-r.com/blog/cdc-slack
* LatinR: https://latin-r.com/cdc/

**Comment by hturner** [comment]
For the specific case of the collaboration campfires, we can use the [Code for Science and Society](https://www.notion.so/Code-of-Conduct-531ca8741bab46218939675f302e0165) code of conduct since we are supported by CS&S cc @SaranjeetKaur.

**Comment by hturner** [comment]
Moved to https://github.com/r-devel/rcontribution/issues/34
