### ISSUE TITLE
Biweekly Bug

### ISSUE THREAD

**Issue by hturner** [r-devel/rcontribution#37]
It may help engagement in bug triage if we regularly featured an open bug on Slack/Twitter, that is either suitable for newbies or where help is particularly wanted (marked as #helpwanted by R core, or seems to be stuck waiting for someone with particular expertise).

"Bug of the Week" is probably too ambitious and hard to maintain, while "Bug of the Month" doesn't seem frequent enough to get much traction. Hence suggestion of "Biweekly Bug".

**Comment by eliocamp** [comment]
I like this. 
Would that work in a "screencast" format? One person takes the reigns and tries to fix the bug with some audience participation? It might attract people who don't feel comfortable being actively involved but prefer o "lurk".

**Comment by hturner** [comment]
At the R Contribution Working Group meeting, it was thought that it might be too much work to come up with a steady stream of bugs suitable for newcomers. Potentially co-working on bugs could happen in the proposed Office Hours (https://github.com/r-devel/rcontribution/issues/32#issuecomment-1249492746) if someone comes with a bug they want to work on, or if a facilitator has seen a suitable bug beforehand. But this could happen on a more ad-hoc basis.
